Update devsecops-sast-sca-Dast-sec-docker.yaml

diff --git a/.github/workflows/devsecops-sast-sca-Dast-sec-docker.yaml b/.github/workflows/devsecops-sast-sca-Dast-sec-docker.yaml
--- a/.github/workflows/devsecops-sast-sca-Dast-sec-docker.yaml
+++ b/.github/workflows/devsecops-sast-sca-Dast-sec-docker.yaml
@@ -14,8 +14,18 @@ jobs:
       - uses: actions/checkout@v4
       - name: Install Flake8
         run: pip install flake8
+      - name: Create Flake8 Config
+        run: |
+          echo "[flake8]" > .flake8
+          echo "max-line-length = 120" >> .flake8
+          echo "exclude = __init__.py" >> .flake8
       - name: Run lint
-        run: flake8 --config=.flake8 flask-app/*.py
+        run: |
+          if [ -f .flake8 ]; then
+            flake8 --config=.flake8 flask-app/*.py
+          else
+            echo "Flake8 config not found!" && exit 1
+          fi
 
   test:
     runs-on: ubuntu-latest
